version: '3'
services:
  mongodb:
    image: 'bitnami/mongodb'
    container_name: mongodb
    environment:
      - MONGODB_USERNAME=vader
      - MONGODB_PASSWORD=notmyfather
      - MONGODB_DATABASE=starwas_planet_api
    labels:
      kompose.service.type: nodeport
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'