version: '3'
services:
  mongodb:
    image: 'bitnami/mongodb'
    container_name: mongodb
    environment:
      - MONGODB_USERNAME=vader
      - MONGODB_PASSWORD=notmyfather
      - MONGODB_DATABASE=starwars_planet_api
    labels:
      kompose.service.type: nodeport
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=notmyfather
    ports:
      - '6379:6379'